# Generated by Django 4.0.6 on 2022-09-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0014_python'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adds_property1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.TextField()),
                ('Stater', models.TextField()),
                ('District', models.TextField()),
                ('Local_Address', models.TextField()),
                ('Description', models.TextField()),
                ('Rent', models.TextField()),
                ('Mobile', models.TextField()),
            ],
        ),
    ]
