# Generated by Django 4.0.6 on 2022-09-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0015_adds_property1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField()),
                ('Email', models.TextField()),
                ('Password', models.TextField()),
                ('Fname', models.TextField()),
                ('Mobile', models.TextField()),
            ],
        ),
    ]
