# Generated by Django 4.0.6 on 2022-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0016_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.TextField()),
                ('Name', models.TextField()),
                ('Mobile', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
