# Generated by Django 4.0.6 on 2022-09-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0017_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adds_property1',
            old_name='Email',
            new_name='Uid',
        ),
    ]
