# Generated by Django 4.0.6 on 2022-09-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loona', '0018_rename_email_adds_property1_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.TextField()),
                ('Name', models.TextField()),
                ('Mobile', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
